//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "gipsobob", table_name = "giveaways")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub ends_at: DateTimeWithTimeZone,
    pub prize: i32,
    pub guild_id: i64,
    pub channel_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::giveaway_participants::Entity")]
    GiveawayParticipants,
}

impl Related<super::giveaway_participants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GiveawayParticipants.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::giveaway_participants::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::giveaway_participants::Relation::Giveaways
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
