//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod dl;
pub mod dl_monsters;
pub mod giveaway_participants;
pub mod giveaways;
pub mod harems;
pub mod marriages;
pub mod quests;
pub mod sbp_invites;
pub mod sbp_users;
pub mod users;
