//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "gipsobob", table_name = "quests")]
pub struct Model {
    #[sea_orm(column_type = "Text")]
    pub id: String,
    pub user_id: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Text")]
    pub action_type: String,
    pub reward: i32,
    pub progress: i32,
    pub progress_max: i32,
    pub ends: Option<i32>,
    pub is_users_required: i32,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    pub users: Option<Vec<i64>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
